import Head from 'next/head'
import Mega_Sena from "../components/Mega_Sena";

export default function mega_sena_page() {

    return <>
        <Head>
            <title>Mega Sena Bet Generator</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div style={{
            border: "1px solid #000;",
            backgroundColor: "#282a36",
            color: "#f8f8f2",
            height: "100vh"
    }}>
            <Mega_Sena></Mega_Sena>
        </div>
    </>
}